0.4.3 (#10)

diff --git a/scripts/bscroll b/scripts/bscroll
--- a/scripts/bscroll
+++ b/scripts/bscroll
@@ -1,7 +1,7 @@
 #!/bin/bash
 
-if ! type i3_news > /dev/null; then
-    echo "i3_news binary not found in the system"
+if ! type i3-news > /dev/null; then
+    echo "i3-news binary not found in the system"
     exit 1
 fi
 
@@ -25,8 +25,8 @@ fi
 if [ -z ${I3_NEWS_OUTPUT_PANGO+x} ]; then
     export I3_NEWS_OUTPUT_PANGO=0
 fi
-if [ -z ${I3_NEWS_BIN_PATH+x} ]; then
-    export I3_NEWS_BIN_PATH=i3_news
+if [ -z "$I3_NEWS_BIN_PATH" ]; then
+    export I3_NEWS_BIN_PATH=i3-news
 fi
 
 
@@ -189,9 +189,9 @@ do
             url=$($cmd)
         fi
         if [ -z ${I3_NEWS_BROWSER_CMD+x} ]; then
-            xdg-open "$url" &
+            xdg-open "$url" > /dev/null &
         else
-            $I3_NEWS_BROWSER_CMD "$url" &
+            $I3_NEWS_BROWSER_CMD "$url" > /dev/null &
         fi
         sleep 1
         if [ "$I3_NEWS_CONTINUOUS_SCROLL" -eq 0 ]; then
diff --git a/scripts/paginate b/scripts/paginate
--- a/scripts/paginate
+++ b/scripts/paginate
@@ -2,12 +2,12 @@
 
 #shellcheck disable=SC2162
 
-if [ -z ${I3_NEWS_BIN_PATH+x} ]; then
-    export I3_NEWS_BIN_PATH=i3_news
+if [ -z "$I3_NEWS_BIN_PATH" ]; then
+    export I3_NEWS_BIN_PATH=i3-news
 fi
 
-if ! type i3_news > /dev/null; then
-    echo "i3_news binary not found in the system"
+if ! type i3-news > /dev/null; then
+    echo "i3-news binary not found in the system"
     exit 1
 fi
 
@@ -143,11 +143,12 @@ do
         cmd="$I3_NEWS_BIN_PATH --get-url $PARAMS"
         url=$($cmd)
         if [ -z ${I3_NEWS_BROWSER_CMD+x} ]; then
-            xdg-open "$url" &
+            xdg-open "$url" > /dev/null &
         else
-            $I3_NEWS_BROWSER_CMD "$url" &
+            $I3_NEWS_BROWSER_CMD "$url" > /dev/null &
         fi
-        sleep 1
+        sleep 2
+        continue
     fi
     NOW=$(date +%s)
     SWITCH=0
